### ISSUE TITLE
Please add our CVPR 2022 paper on Semantic Segmentation

### ISSUE THREAD

**Issue by BinhuiXie** [amusi/CVPR2022-Papers-with-Code#119]
Hi @amusi

We request to add our new work RIPU to this awesome repo.

Title: Towards Fewer Annotations: Active Learning via Region Impurity and Prediction Uncertainty for Domain Adaptive Semantic Segmentation

paper: https://arxiv.org/pdf/2111.12940.pdf
code: https://github.com/BIT-DA/RIPU

Thank you!

**Comment by amusi** [comment]
Now the project has been added, thanks for sharing
