### ISSUE TITLE
Please add our CVPR2022 (oral) paper TransRAC on the Repitition Counting category

### ISSUE THREAD

**Issue by zhao-yiqun** [amusi/CVPR2022-Papers-with-Code#120]
Title: TransRAC: Encoding Multi-scale Temporal Correlation with Transformers for Repetitive Action Counting

arxiv: [https://arxiv.org/pdf/2204.01018.pdf](https://arxiv.org/pdf/2204.01018.pdf)
code: [https://github.com/SvipRepetitionCounting/TransRAC](https://github.com/SvipRepetitionCounting/TransRAC)

**Comment by zhao-yiqun** [comment]
It can also be included in the Video Understanding category~

**Comment by amusi** [comment]
Now the project has been added, thanks for sharing
