### ISSUE TITLE
Please add our CVPR 2022 paper on Semi-supervised Semantic Segmentation

### ISSUE THREAD

**Issue by tianyu0207** [amusi/CVPR2022-Papers-with-Code#121]
Perturbed and Strict Mean Teachers for Semi-supervised Semantic Segmentation
Topic on: semi-supervised semantic segmentation/ semantic segmentation / semi-supervised learning 

Paper: https://arxiv.org/pdf/2111.12903.pdf
Code: https://github.com/yyliu01/PS-MT

**Comment by amusi** [comment]
Now the project has been added, thanks for sharing
