### ISSUE TITLE
Please add our CVPR 2022 paper on Semi-supervised learning in medical images 

### ISSUE THREAD

**Issue by tianyu0207** [amusi/CVPR2022-Papers-with-Code#122]
ACPL: Anti-curriculum Pseudo-labelling for Semi-supervised Medical Image Classification
Topic on: semi-supervised learning/ medical imaging

Paper: https://arxiv.org/pdf/2111.12918.pdf
Code: https://github.com/FBLADL/ACPL

**Comment by amusi** [comment]
Now the project has been added, thanks for sharing
