### ISSUE TITLE
Please add our CVPR 2022 paper on Visual Transformer-Application

### ISSUE THREAD

**Issue by jhcho99** [amusi/CVPR2022-Papers-with-Code#128]
Thanks for this great repository!! Please add our paper on Visual Transformer-Application. 

**Collaborative Transformers for Grounded Situation Recognition**  

Paper: https://arxiv.org/abs/2203.16518
Code: https://github.com/jhcho99/CoFormer

**Comment by amusi** [comment]
Now the project has been added, thanks for sharing
