### ISSUE TITLE
Please add our CVPR 2022 paper on Few-shot Learning/Classification

### ISSUE THREAD

**Issue by LouieYang** [amusi/CVPR2022-Papers-with-Code#129]
Please add our paper on Few-shot Learning/Classification; thanks.

Learning to Affiliate: Mutual Centralized Learning for Few-shot Classification

Paper: https://arxiv.org/abs/2106.05517
Code: https://github.com/LouieYang/MCL

**Comment by amusi** [comment]
Now the project has been added, thanks for sharing
