### ISSUE TITLE
Please add our CVPR 2022 paper on semantic segmentation

### ISSUE THREAD

**Issue by HeliosZhao** [amusi/CVPR2022-Papers-with-Code#130]
Please add our CVPR 2022 paper on semantic segmentation, thanks.

Novel Class Discovery in Semantic Segmentation

Paper: https://arxiv.org/pdf/2112.01900.pdf
Project page: https://ncdss.github.io/
Code: https://github.com/HeliosZhao/NCDSS

**Comment by amusi** [comment]
Now the project has been added, thanks for sharing
