### ISSUE TITLE
Introducing our work Robust and Accurate Superquadric Recovery: a Probabilistic Approach

### ISSUE THREAD

**Issue by bmlklwx** [amusi/CVPR2022-Papers-with-Code#132]
Thanks for your work. I would be appreciate if you could add our work:

Robust and Accurate Superquadric Recovery: a Probabilistic Approach

Paper (Oral):
https://arxiv.org/abs/2111.14517

Codes:
https://github.com/bmlklwx/EMS-superquadric_fitting

**Comment by amusi** [comment]
Now the project has been added, thanks for sharing
