### ISSUE TITLE
Please add our CVPR 2022 paper on Weakly Supervised Learning

### ISSUE THREAD

**Issue by Sierkinhane** [amusi/CVPR2022-Papers-with-Code#133]
Great repository! Please add our CVPR 2022 paper on Weakly Supervised Learning

CCAM: Contrastive learning of Class-agnostic Activation Map for Weakly Supervised Object Localization and Semantic Segmentation
Paper: https://arxiv.org/abs/2203.13505
Code: https://github.com/CVI-SZU/CCAM

------------------------------------------------------------------------------------------------------------------------------------------

CLIMS: Cross Language Image Matching for Weakly Supervised Semantic Segmentation
Paper: https://arxiv.org/abs/2203.02668
Code: https://github.com/CVI-SZU/CLIMS

**Comment by amusi** [comment]
Now the project has been added, thanks for sharing
