### ISSUE TITLE
Please add our CVPR 2022 paper on semantic segmentation (an oral presentation)

### ISSUE THREAD

**Issue by sohyun-l** [amusi/CVPR2022-Papers-with-Code#135]
Please add our CVPR 2022 oral paper on semantic segmentation.

Title: FIFO: Learning Fog-invariant Features for Foggy Scene Segmentation
Paper url: https://arxiv.org/pdf/2204.01587.pdf
Project page: http://cvlab.postech.ac.kr/research/FIFO/
Code: https://github.com/sohyun-l/FIFO (will be released soon)

Thank you!

**Comment by amusi** [comment]
Now the project has been added, thanks for sharing
