### ISSUE TITLE
Please add our CVPR 2022 paper on 3D face modeling

### ISSUE THREAD

**Issue by MingwuZheng** [amusi/CVPR2022-Papers-with-Code#136]
Please add our CVPR 2022 paper on 3D face modeling.

Title: ImFace: A Nonlinear 3D Morphable Face Model with Implicit Neural Representations
Paper url: https://arxiv.org/abs/2203.14510
Code: https://github.com/MingwuZheng/ImFace (will be released soon)

Thank you!

**Comment by amusi** [comment]
Now the project has been added, thanks for sharing
