### ISSUE TITLE
Please add BEV (CVPR22) to 3D人体姿态估计(3D Human Pose Estimation)

### ISSUE THREAD

**Issue by Arthur151** [amusi/CVPR2022-Papers-with-Code#138]
BEV: Putting People in their Place: Monocular Regression of 3D People in Depth

Code: https://github.com/Arthur151/ROMP
Paper: https://arxiv.org/abs/2112.08274
Dataset: https://github.com/Arthur151/Relative_Human
Video: https://www.youtube.com/watch?v=Q62fj_6AxRI
Project page: https://arthur151.github.io/BEV/BEV.html

**Comment by amusi** [comment]
Now the project has been added, thanks for sharing
