### ISSUE TITLE
Please add our CVPR 2022 paper on 3D point cloud

### ISSUE THREAD

**Issue by chrockey** [amusi/CVPR2022-Papers-with-Code#140]
Hi,

I would be grateful if you could add our paper, _Fast Point Transformer_.

Paper title: Fast Point Transformer
Paper link: https://arxiv.org/abs/2112.04702
Code link: https://github.com/POSTECH-CVLab/FastPointTransformer

Thank you!

**Comment by amusi** [comment]
Now the project has been added, thanks for sharing
