### ISSUE TITLE
Please add our CVPR 2022 paper on semantic segmentation.

### ISSUE THREAD

**Issue by tfzhou** [amusi/CVPR2022-Papers-with-Code#143]
Please add our two papers on semantic segmentation. Thanks!

[Semantic Segmentation]
Paper name/title: Rethinking Semantic Segmentation: A Prototype View
Paper link: https://arxiv.org/abs/2203.15102
Code link: https://github.com/tfzhou/ProtoSeg

[Weakly Supervised Semantic Segmentation]
Paper name/title: Regional Semantic Contrast and Aggregation for Weakly Supervised Semantic Segmentation
Paper link: https://arxiv.org/abs/2203.09653
Code link: https://github.com/maeve07/RCA.git

**Comment by tfzhou** [comment]
Please add one more paper on semantic segmentation. Thanks!

[Semantic Segmentation]
Paper name/title: Deep Hierarchical Semantic Segmentation
Paper link: https://arxiv.org/abs/2203.14335
Code link: https://github.com/0liliulei/HieraSeg

**Comment by amusi** [comment]
Now the project has been added, thanks for sharing
