### ISSUE TITLE
Please add our CVPR 2022 paper on GAN.

### ISSUE THREAD

**Issue by raven38** [amusi/CVPR2022-Papers-with-Code#144]
Hi,

I would be grateful if you could add our paper, OSSGAN

Paper title:OSSGAN: Open-set Semi-supervised Image Generation
Paper link: https://arxiv.org/abs/2204.14249
Code link: https://github.com/raven38/OSSGAN
Thank you!

**Comment by amusi** [comment]
Now the project has been added, thanks for sharing
