### ISSUE TITLE
Please add our CVPR 2022 paper on self-supervised video correspondence learning.

### ISSUE THREAD

**Issue by 0liliulei** [amusi/CVPR2022-Papers-with-Code#151]
Please add our CVPR 2022 paper on self-supervised video correspondence learning.

Title: Locality-Aware Inter-and Intra-Video Reconstruction for Self-Supervised Correspondence Learning
Paper url: https://arxiv.org/abs/2203.14333
Code: https://github.com/0liliulei/LIIR (will be released soon)

By the way, this paper ["Rethinking Semantic Segmentation: A Prototype View"](https://github.com/amusi/CVPR2022-Papers-with-Code/blob/8294bb306aa839f9095f1f557b2bb94a2dd490b8/README.md?plain=1#L683)  is an oral presentation, please add a special note to indicate this.

Thanks a lot !

**Comment by amusi** [comment]
Now the project has been added, thanks for sharing
