### ISSUE TITLE
Please add our CVPR 2022 paper on Video Panoptic Segmentation/Datasets contribution

### ISSUE THREAD

**Issue by VIPSeg-Dataset** [amusi/CVPR2022-Papers-with-Code#152]
Please add our CVPR 2022 paper on  Video Panoptic Segmentation/Datasets contribution.

Title: Large-scale Video Panoptic Segmentation in the Wild: A Benchmark
Paper url: https://github.com/VIPSeg-Dataset/VIPSeg-Dataset/blob/main/VIPSeg2022.pdf
Code: https://github.com/VIPSeg-Dataset/VIPSeg-Dataset
Dataset: https://github.com/VIPSeg-Dataset/VIPSeg-Dataset

Thanks!

**Comment by amusi** [comment]
Now the project has been added, thanks for sharing
