### ISSUE TITLE
Please add our CVPR 2022 paper on 3D Point Cloud or Others contribution

### ISSUE THREAD

**Issue by gxd1994** [amusi/CVPR2022-Papers-with-Code#155]
Paper title: RCP: Recurrent Closest Point for Scene Flow Estimation on 3D Point Clouds
Paper link: https://arxiv.org/abs/2205.11028
Code link: https://github.com/gxd1994/RCP
Thanks!

**Comment by amusi** [comment]
Now the project has been added, thanks for sharing
